/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as LivestockRouteImport } from './routes/livestock'
import { Route as SoilRouteImport } from './routes/soil'
import { Route as WaterRouteImport } from './routes/water'
import { Route as WeatherRouteImport } from './routes/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestockRoute = LivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilRoute = SoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crops': typeof CropsRoute
  '/livestock': typeof LivestockRoute
  '/soil': typeof SoilRoute
  '/water': typeof WaterRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crops': typeof CropsRoute
  '/livestock': typeof LivestockRoute
  '/soil': typeof SoilRoute
  '/water': typeof WaterRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crops': typeof CropsRoute
  '/livestock': typeof LivestockRoute
  '/soil': typeof SoilRoute
  '/water': typeof WaterRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crops' | '/livestock' | '/soil' | '/water' | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crops' | '/livestock' | '/soil' | '/water' | '/weather'
  id:
    '__root__' | '/' | '/crops' | '/livestock' | '/soil' | '/water' | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropsRoute: typeof CropsRoute
  LivestockRoute: typeof LivestockRoute
  SoilRoute: typeof SoilRoute
  WaterRoute: typeof WaterRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestock': {
      id: '/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof LivestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil': {
      id: '/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof SoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropsRoute: CropsRoute,
  LivestockRoute: LivestockRoute,
  SoilRoute: SoilRoute,
  WaterRoute: WaterRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
